# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# test_name:
#  stage: allowed names: .pre, build, test, deploy, .post
#  image: the image to be used, make sure it's specific!!
#  before_script: To make sure the command to be run in the job is installed
#   - the command to be run before the actual script part
#  script: 
#  - command to run the test, look into jest
#   after_script:
#     - Same as before script, except after
#  More about command: for the job to be executed: command available, pip (npm), python (javascript(?))
# Will always run inside a docker container, hence why an image is required
# So I will need an image that has npm and javascript?
stages: 
- test
- build
- deploy
- my-custom-stage


build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

own-test:
  stage: test
  script:
    - echo "Is this working?"

test-job1:
  stage: my-custom-stage
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
